### ISSUE TITLE
HttpError 404 not found 

### ISSUE THREAD

**Issue by GreenLeon23** [WolfPlugs/osu#2]
If I type any name it just sends this 
![image](https://user-images.githubusercontent.com/50149894/128219373-9e204dda-0f5b-4ed2-9b0b-b92edbff0943.png)

**Comment by megahello** [comment]
It seems that part of the API disappeared. Not sure.

**Comment by slopslug** [comment]
Never messed around with the osu API before, but could it be that we need to supply our own keys for it to work?

**Comment by megahello** [comment]
It was using the `Obamabot` API.

**Comment by Wolfkid200444** [comment]
The issue has been fixed on 34c9659
